src/Rizzen/ForumBundle/Entity/Message.php
<?php

namespace Rizzen\ForumBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Message
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Rizzen\ForumBundle\Entity\MessageRepository")
 */
class Message
{
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->date = new \DateTime('now');
        $this->originalPost = false;
        $this->visible = true;
        $this->isLocked = false;
    }

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     *
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = "1",
     *      max = "11000"
     * )
     */
    protected $content;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetimetz")
     */
    protected $date;

    /**
     * @var string
     *
     * @ORM\Column(name="creatorIp", type="cidr")
     */
    protected $creatorIp;

    /**
     * @ORM\ManyToOne(targetEntity="Rizzen\UserBundle\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $creator;

    /**
     * @var boolean
     *
     * @ORM\Column(name="visible", type="boolean")
     */
    protected $visible;

    /**
     * @ORM\ManyToOne(targetEntity="Thread", inversedBy="messages")
     */
    protected $thread;

    /**
     * @var boolean
     *
     * @ORM\Column(name="isLocked", type="boolean", nullable=true)
     */
    protected $isLocked;

    /**
     * @var boolean
     *
     * @ORM\Column(name="originalPost", type="boolean")
     */
    protected $originalPost;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Message
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Message
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set creatorIp
     *
     * @param string $creatorIp
     * @return Message
     */
    public function setCreatorIp($creatorIp)
    {
        $this->creatorIp = $creatorIp;

        return $this;
    }

    /**
     * Get creatorIp
     *
     * @return string
     */
    public function getCreatorIp()
    {
        return $this->creatorIp;
    }

    /**
     * Set visible
     *
     * @param boolean $visible
     * @return Message
     */
    public function setVisible($visible)
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * Get visible
     *
     * @return boolean
     */
    public function isVisible()
    {
        return $this->visible;
    }

    /**
     * Set creator
     *
     * @param \Rizzen\UserBundle\Entity\User $creator
     * @return Message
     */
    public function setCreator(\Rizzen\UserBundle\Entity\User $creator)
    {
        $this->creator = $creator;

        return $this;
    }

    /**
     * Get creator
     *
     * @return \Rizzen\UserBundle\Entity\User
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Set thread
     *
     * @param \Rizzen\ForumBundle\Entity\Thread $thread
     * @return Message
     */
    public function setThread(\Rizzen\ForumBundle\Entity\Thread $thread = null)
    {
        $this->thread = $thread;

        return $this;
    }

    /**
     * Get thread
     *
     * @return \Rizzen\ForumBundle\Entity\Thread
     */
    public function getThread()
    {
        return $this->thread;
    }

    /**
     * Set isLocked
     *
     * @param boolean $isLocked
     * @return Message
     */
    public function setLocked($isLocked)
    {
        $this->isLocked = $isLocked;

        return $this;
    }

    /**
     * Get isLocked
     *
     * @return boolean 
     */
    public function isLocked()
    {
        return $this->isLocked;
    }

    /**
     * Set originalPost
     *
     * @param boolean $originalPost
     *
     * @return Message
     */
    public function setOriginalPost($originalPost)
    {
        $this->originalPost = $originalPost;

        return $this;
    }

    /**
     * Get originalPost
     *
     * @return boolean
     */
    public function isOriginalPost()
    {
        return $this->originalPost;
    }
}

src/Rizzen/ForumBundle/Controller/ForumController.php
<?php

namespace Rizzen\ForumBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Rizzen\ForumBundle\Entity\Thread;
use Rizzen\ForumBundle\Entity\Message;
use Rizzen\ForumBundle\Form\Type\ThreadType;
use Rizzen\ForumBundle\Form\Type\MessageType;
use Rizzen\ForumBundle\Entity\SubCategory;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class ForumController extends Controller
{
    /**
     * The forum index
     *
     * @param string $subdomain     Guild subdomain
     * @return Response
     */
    public function indexAction($subdomain)
    {
        $guild = $this->get('get.guild')->getGuild($subdomain);

        $permissionsManager = $this->get('permissions.manager')->setGuild($guild)->setUser($this->getUser());

        $categories = $this->getDoctrine()->getRepository('RizzenForumBundle:Category')->getCategories($guild->getForum());

        $categories = $this->get('forum.viewable')->getAccessibleCategories($categories, $permissionsManager->getPermissions());

        return $this->render('RizzenForumBundle:Forum:index.html.twig', [
            'guild' => $guild,
            'subdomain' => $subdomain,
            'categories' => $categories,
            'permissions' => $permissionsManager->getPermissions()
        ]);
    }

    /**
     * Join the forum of a guild
     *
     * @param string $subdomain     Guild subdomain
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function joinAction($subdomain, Request $request)
    {
        $this->denyAccessUnlessGranted('fos_user_security_login');

        $guild = $this->get('get.guild')->getGuild($subdomain);

        $permissionsManager = $this->get('permissions.manager')->setGuild($guild)->setUser($this->getUser());

        if ($permissionsManager->isForumMember(false)) {
            throw $this->createNotFoundException('Page not found, you might already be registered to this forum.');
        }

        $this->get('forum.manager')->joinForum($guild, $this->getUser());

        if ($request->headers->get('referer') === null) {
            return $this->redirectToRoute('rizzen_forum_see', ['subdomain' => $subdomain]);
        } else {
            return $this->redirect($request->headers->get('referer'), 301);
        }

    }

    /**
     * @param string $subdomain     Guild subdomain
     * @param string $slug          SubCategory slug
     * @param int $page             Current page
     * @return Response
     */
    public function subCategoryAction($subdomain, $slug, $page)
    {
        $subCategory = $this->get('forum.manager')->getSubCategory($slug);
        $guild = $this->get('get.guild')->getGuild($subdomain);

        $permissionsManager = $this->get('permissions.manager')->setGuild($guild)->setUser($this->getUser());

        $this->get('forum.viewable')->canSee($subCategory, $permissionsManager->getPermissions(), true);
        $threads = $this->getDoctrine()->getRepository('RizzenForumBundle:Thread')->getAllVisibleThreadsInSubCategory($subCategory);
        $pagination = $this->get('knp_paginator')->paginate($threads, $page, 10);

        return $this->render('RizzenForumBundle:Forum:subcat.html.twig', [
            'subcat' => $subCategory,
            'subdomain' => $subdomain,
            'guild' => $guild,
            'threads' => $pagination,
            'permissions' => $permissionsManager->getPermissions()
        ]);
    }

    /**
     * Figure out what the last page is, and forward to it
     *
     * @param string $subdomain Guild subdomain
     * @param string $slug SubCategory Slug
     * @param string $threadSlug Thread Slug
     * @param Request $request
     * @return Response
     */
    public function threadLatestMessageAction($subdomain, $slug, $threadSlug, Request $request)
    {
        $thread = $this->get('forum.manager')->getThreadOrNotFound($threadSlug, $slug, $subdomain);
        $messageCount = $this->getDoctrine()->getRepository('RizzenForumBundle:Message')->getMessageCount($thread);

        $lastPage = $messageCount < 1
            ? 1
            : ceil($messageCount / 8);

        $request->request->add(['seeLatestMessage' => true]);

        return $this->forward('RizzenForumBundle:Forum:seeThread', [
                'subdomain'  => $subdomain,
                'slug' => $slug,
                'threadSlug' => $threadSlug,
                'page' => $lastPage
            ]
        );
    }

    /**
     * Search for threads the forum in all the the categories the user can access
     * This search is limited in the number of results in can output.
     *
     * @param string $subdomain
     * @param string $query
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function searchAction($subdomain, $query)
    {
        $guild = $this->get('get.guild')->getGuild($subdomain);

        $searchManipulator = $this->get('thread.search.manipulator');

        $query = $searchManipulator->cleanSearchQuery($query);

        if ($query === false) {
            $this->addFlash('error', 'The search query is too long or too short. The query must contain at least 3 characters and a maximum of 40.');
            return $this->redirectToRoute('rizzen_forum_see', ['subdomain' => $subdomain]);
        }

        $permissionsManager = $this->get('permissions.manager')->setGuild($guild)->setUser($this->getUser());

        $threads = $this->getDoctrine()->getRepository('RizzenForumBundle:Thread')->searchThread($query, $guild->getForum(), $this->getUser());
        $threads = $searchManipulator->cleanSearchResults($threads, $this->getUser(), $guild);

        $threadVisits = $this->get('forum.thread.visits')->getThreadVisits($threads, $guild);

        return $this->render('RizzenForumBundle:Forum:search.html.twig', [
            'subdomain' => $subdomain,
            'threadVisits' => $threadVisits,
            'query' => urldecode($query),
            'guild' => $guild,
            'threads' => $threads,
            'permissions' => $permissionsManager->getPermissions()
        ]);
    }

    /**
     * Search for threads in a sub category
     *
     * @param string $subdomain
     * @param string $slug
     * @param string $query
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function searchSubCatAction($subdomain, $slug, $query, $page)
    {
        $guild = $this->get('get.guild')->getGuild($subdomain);
        $subcat = $this->get('forum.manager')->getSubCategory($slug);

        $permissionsManager = $this->get('permissions.manager')->setGuild($guild)->setUser($this->getUser());
        $this->get('forum.viewable')->canSee($subcat, $permissionsManager->getPermissions(), true);

        $searchManipulator = $this->get('thread.search.manipulator');

        $query = $searchManipulator->cleanSearchQuery($query);

        if ($query === false) {
            $this->addFlash('error', 'The search query is too long or too short. The query must contain at least 3 characters and a maximum of 40.');
            return $this->redirectToRoute('rizzen_forum_see', ['subdomain' => $subdomain]);
        }

        $threads = $this->getDoctrine()->getRepository('RizzenForumBundle:Thread')->searchThreadInSubCategory($query, $subcat);

        $pagination = $this->get('knp_paginator')->paginate($threads, $page, 10);
        $threadVisits = $this->get('forum.thread.visits')->getThreadVisits($pagination, $guild, true);

        return $this->render('RizzenForumBundle:Forum:searchSubcat.html.twig', [
                'subdomain' => $subdomain,
                'guild' => $guild,
                'threadVisits' => $threadVisits,
                'subcat' => $subcat,
                'query' => urldecode($query),
                'threads' => $pagination,
                'permissions' => $permissionsManager->getPermissions()
            ]
        );
    }

    /**
     * The thread page
     *
     * @param string $subdomain     Guild subdomain
     * @param string $slug          SubCategory Slug
     * @param string $threadSlug    Thread Slug
     * @param int $page             Current page
     * @return Response
     */
    public function seeThreadAction($subdomain, $slug, $threadSlug, $page)
    {
        $thread = $this->get('forum.manager')->getThreadOrNotFound($threadSlug, $slug, $subdomain);
        $threadMessages = $this->getDoctrine()->getRepository('RizzenForumBundle:Message')->getThreadContent($thread);

        $guild = $thread->getSubCategory()->getCategory()->getForum()->getGuild();
        $permissionsManager = $this->get('permissions.manager')->setGuild($guild)->setUser($this->getUser());
        $this->get('forum.viewable')->canSee($thread, $permissionsManager->getPermissions(), true);

        $categories = $this->get('forum.viewable')->getCategoriesForThreadMove($thread, $permissionsManager->getPermissions());

        $form = null;
        $editForm = null;

        $pagination = $this->get('knp_paginator')->paginate($threadMessages, $page, 8);
        $pagination->setUsedRoute('rizzen_forum_thread');

        if ($permissionsManager->isForumMember(false)) {
            $message = new Message();
            $form = $this->createForm(MessageType::class, $message)->createView();

            $editForm = $this->createFormBuilder([])
                ->add('content', TextareaType::class)
                ->add('target', HiddenType::class)
                ->add('lock', CheckboxType::class, ['required' => false])
                ->getForm()->createView();
        }

        return $this->render('RizzenForumBundle:Forum:thread.html.twig', [

src/Rizzen/ForumBundle/Resources/views/Forum/search.html.twig
{% extends '::base.html.twig' %}
{% block meta %}
<meta name="robots" content="noindex,nofollow">
{% endblock %}

{% block title %}Searching - Forum - {% endblock %}

{% block TopBarButtons %}

    {% if permissions.isForumMember == false and permissions.isBannedFromForum == false %}
        <li><span><a href="{{ path("rizzen_forum_join", {'subdomain': subdomain}) }}" class="forum-reg-btn btn btn-primary navbar-btn"><i class="fa fa-check"></i> Join this forum</a></span></li>

    {% elseif permissions.canSeeAdminPanel %}

        {% include '::administrationDropdown.html.twig' %}

    {% endif %}

{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-8">
            <ol class="breadcrumb breadcrumb-arrow">
                <li><a href="{{ path('rizzen_guild_see', {'subdomain': subdomain}) }}"><i class="fa fa-home"></i> {{ guild.title }}</a></li>
                <li><a href="{{ path('rizzen_forum_see', {'subdomain': subdomain}) }}"><i class="fa fa-comments"></i> Forum index</a></li>
                <li class="active"><span><i class="fa fa-search"></i> Searching</span></li>
            </ol>
        </div>
        {% include 'RizzenForumBundle:Forum:searchField.html.twig' with {'generalSearch': true} %}
        <br/>
    </div>

    <div class="row">

        <div class="col-md-12">
            <div class="panel panel-primary forum-list-panel">
                <div class="panel-heading">
                    {% if threads | length == 0 %}
                        <h3 class="panel-title"><i class="fa fa-comments-o"></i> Sorry, we didn't find anything.</h3>
                    {% elseif threads | length == 1 %}
                        <h3 class="panel-title"><i class="fa fa-comments-o"></i> A single thread was found.</h3>
                    {% elseif threads | length > 1 and threads | length < 10 %}
                        <h3 class="panel-title"><i class="fa fa-comments-o"></i> {{ threads | length }} threads were found.</h3>
                    {% else %}
                        <h3 class="panel-title"><i class="fa fa-comments-o"></i> Displaying 15 results, but there might be more, search from a sub-category to find more threads.</h3>
                    {% endif %}
                </div>



                {% for thread in threads  %}

                    <div class="forum-list-subcat {% if loop.index is even %}forum-list-alternate{% endif %}">
                        <div class="row">
                            <a href="{{ path("rizzen_forum_thread_history", {'subdomain': subdomain, 'slug': thread.subCategory.slug, 'threadSlug': thread.slug}) }}" class="text-color-reset">
                                <div class="col-md-8 col-sm-8 col-xs-10 subcat-thread-pad">
                                    <h4 class="no-margin">{{ thread.title }}</h4>
                                    <p>
                                        {% if thread.locked %}<span class="label label-danger"><i class="fa fa-lock"></i> <span class="hidden-xs">Locked</span></span> | {% endif %}

                                        <small>
                                            <i class="fa fa-info-circle"></i> <strong title="Category">{{ thread.subCategory.category.title }}</strong>
                                            <i class="fa fa-angle-double-right"></i> <span title="Sub-category">{{ thread.subCategory.title }}</span> |
                                            By <strong>{{ thread.creator.username }}</strong> {{ thread.date | ago }}
                                        </small>
                                    </p>

                                </div>
                            </a>

                            <div class="col-md-2 col-sm-2 hidden-xs">
                                <div class="pull-right">
                                    {{ thread.messagesCount }} <i class="fa fa-comments"></i>
                                </div>
                                <br/>
                                <div class="pull-right">
                                    {% if threadVisits[loop.index0] is null %}0{% else %}{{ threadVisits[loop.index0] }}{% endif %} <i class="fa fa-eye"></i>
                                </div>
                            </div>

                            <a rel="nofollow" href="{{ path("rizzen_forum_thread_latest", {'subdomain': subdomain, 'slug': thread.subCategory.slug, 'threadSlug': thread.slug}) }}" class="text-color-reset">
                                <div class="col-md-2 col-xs-2 forum-list-last-message-separator">

                                    <img class="pull-left forum-list-avatar img-rounded" src="{{ thread.lastMessage.creator.avatar.webPath | imagine_filter('avatar_forum') }}" alt="User avatar">
                                    <div class="forum-list-last-message hidden-xs">
                                        <strong>{{ thread.lastMessage.creator.username }}</strong>
                                        <hr class="no-margin"/>
                                        <small>{{ thread.lastMessage.date|ago }}</small>
                                    </div>
                                </div>
                            </a>

                        </div>
                    </div>

                    <hr class="no-margin"/>
                {% endfor %}

            </div>
        </div>

    </div>


    <div class="row">
        <div class="col-md-12 ">
            <div class="alert alert-info">
                <i class="fa fa-info-circle"></i> Didn't find what your were looking for? The general search is limited, use the search functionality inside a sub-category to find more threads.
            </div>
        </div>
    </div>


{% endblock %}

{% block customCSS %}
    {% if guild.customCSSEnabled %}
        <link rel="stylesheet" href="{{ asset(guild.customCSSFile) }}"/>
    {% endif %}
{% endblock %}

src/Rizzen/ForumBundle/Resources/views/Forum/searchField.html.twig
<div class="col-md-4">
    <form action="#" id="forumSearchForm">
        <div class="input-group search-height">
            <div id="searchFormGroup" class="form-group">
                {% if generalSearch %}
                    <input {% if query is defined %}value="{{ query }}"{% endif %} id="forumSearchInput" type="text" placeholder="Search in this forum" name="search" class="form-control search-height" autocomplete="off">
                {% else %}
                    <input {% if query is defined %}value="{{ query }}"{% endif %} id="forumSearchInput" type="text" placeholder="Search in this sub-category" name="search" class="form-control search-height" autocomplete="off">
                {% endif %}
                <span id="searchFormErrorIcon" class="glyphicon glyphicon-remove search-height form-control-feedback d-none"></span>
            </div>

            <span class="input-group-btn">
                <button id="forumSearchButton" class="btn btn-primary search-height" onclick="executeForumSearch()" type="button"><i class="fa fa-search"></i><span class="hidden-md hidden-lg"> Search</span></button>
            </span>

        </div>
    </form>
</div>

src/Rizzen/ForumBundle/Resources/views/Forum/searchSubcat.html.twig
{% extends '::base.html.twig' %}
{% block meta %}
    <meta name="robots" content="noindex,nofollow">
{% endblock %}

{% block title %}Searching - {{ subcat.title }} - Forum - {% endblock %}

{% block TopBarButtons %}

    {% if permissions.isForumMember == false and permissions.isBannedFromForum == false %}
        <li><span><a href="{{ path("rizzen_forum_join", {'subdomain': subdomain}) }}" class="forum-reg-btn btn btn-primary navbar-btn"><i class="fa fa-check"></i> Join this forum</a></span></li>

    {% elseif permissions.canSeeAdminPanel %}

        {% include '::administrationDropdown.html.twig' %}

    {% endif %}

{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-8">
            <ol class="breadcrumb breadcrumb-arrow breadcrumb-nowrap">
                <li><a href="{{ path('rizzen_guild_see', {'subdomain': subdomain}) }}"><i class="fa fa-home"></i> {{ guild.title }}</a></li>
                <li><a href="{{ path('rizzen_forum_see', {'subdomain': subdomain}) }}"><i class="fa fa-comments"></i> Forum index</a></li>
                <li><a href="{{ path('rizzen_forum_subcat', {'subdomain': subdomain, 'slug': subcat.slug}) }}"><i class="fa fa-comments-o"></i> {{ subcat.title }}</a></li>
                <li class="active"><span><i class="fa fa-search"></i> Searching</span></li>
            </ol>
        </div>
        {% include 'RizzenForumBundle:Forum:searchField.html.twig' with {'generalSearch': false} %}
        <br/>
    </div>

    <div class="row">

        <div class="col-md-12">
            <div class="panel panel-primary forum-list-panel">
                <div class="panel-heading">
                    {% if threads.getTotalItemCount == 0 %}
                        <h3 class="panel-title"><i class="fa fa-comments-o"></i> Sorry, we didn't find anything.</h3>
                    {% elseif threads.getTotalItemCount == 1 %}
                        <h3 class="panel-title"><i class="fa fa-comments-o"></i> A single thread was found.</h3>
                    {% elseif threads.getTotalItemCount > 1 and threads.getTotalItemCount < 10 %}
                        <h3 class="panel-title"><i class="fa fa-comments-o"></i> {{ threads.getTotalItemCount }} threads were found.</h3>
                    {% else %}
                        <h3 class="panel-title"><i class="fa fa-comments-o"></i> {{ threads.getTotalItemCount }} results found</h3>
                    {% endif %}
                </div>



                {% for thread in threads  %}
                    {% set thread = thread.0 %}

                    <div class="forum-list-subcat {% if loop.index is even %}forum-list-alternate{% endif %}">
                        <div class="row">
                            <a href="{{ path("rizzen_forum_thread_history", {'subdomain': subdomain, 'slug': thread.subCategory.slug, 'threadSlug': thread.slug}) }}" class="text-color-reset">
                                <div class="col-md-8 col-sm-8 col-xs-10 subcat-thread-pad">
                                    <h4 class="no-margin">{{ thread.title }}</h4>
                                    <p>
                                        {% if thread.locked %}<span class="label label-danger"><i class="fa fa-lock"></i> <span class="hidden-xs">Locked</span></span> | {% endif %}


                                        {% if thread.locked %}<span class="label label-danger"><i class="fa fa-lock"></i> <span class="hidden-xs">Locked</span></span> | {% endif %}
                                        <small class="hidden-xs">Thread created by <strong>{{ thread.creator.username }}</strong> {{ thread.date | ago }}</small>
                                        <small class="visible-xs-inline">By <strong>{{ thread.creator.username }}</strong> {{ thread.date | ago }}, last message: {{ thread.lastMessage.date|ago }} by <strong>{{ thread.lastMessage.creator.username }}</strong></small>
                                    </p>

                                </div>
                            </a>

                            <div class="col-md-2 col-sm-2 hidden-xs">
                                <div class="pull-right">
                                    {{ thread.messagesCount }} <i class="fa fa-comments"></i>
                                </div>
                                <br/>
                                <div class="pull-right">
                                    {% if threadVisits[loop.index0] is null %}0{% else %}{{ threadVisits[loop.index0] }}{% endif %} <i class="fa fa-eye"></i>
                                </div>
                            </div>

                            <a rel="nofollow" href="{{ path("rizzen_forum_thread_latest", {'subdomain': subdomain, 'slug': thread.subCategory.slug, 'threadSlug': thread.slug}) }}" class="text-color-reset">
                                <div class="col-md-2 col-xs-2 forum-list-last-message-separator">

                                    <img class="pull-left forum-list-avatar img-rounded" src="{{ thread.lastMessage.creator.avatar.webPath | imagine_filter('avatar_forum') }}" alt="User avatar">
                                    <div class="forum-list-last-message hidden-xs">
                                        <strong>{{ thread.lastMessage.creator.username }}</strong>
                                        <hr class="no-margin"/>
                                        <small>{{ thread.lastMessage.date|ago }}</small>
                                    </div>
                                </div>
                            </a>

                        </div>
                    </div>

                    <hr class="no-margin"/>
                {% endfor %}

            </div>
        </div>

    </div>


    <div class="row">
        <div class="col-md-12">
            <div class="pagination-no-margin pull-right">
                {{ knp_pagination_render(threads) }}
            </div>
        </div>
    </div>


{% endblock %}

{% block customCSS %}
    {% if guild.customCSSEnabled %}
        <link rel="stylesheet" href="{{ asset(guild.customCSSFile) }}"/>
    {% endif %}
{% endblock %}

{% block javascripts %}
    <script>
        var subcatSlug = '{{ subcat.slug | raw }}';
    </script>
{% endblock %}